version: '3.8'

services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: always
    ports:
      - "3000:80"
    environment:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: db
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: wallapass

  db:
    image: mariadb:latest
    container_name: wallabag_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wallabag
      MYSQL_USER: wallabag
      MYSQL_PASSWORD: wallapass

  redis:
    image: redis:alpine
    container_name: wallabag_redis
    restart: always